on:
  issues:
    types: [opened]

name: Jira Actions

jobs:
  build:
    runs-on: ubuntu-latest
    name: Create Jira task
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Jira Create issue
      uses: atlassian/gajira-create@v3
      id: create
      with:
        project: SERLIB
        issuetype: Task
        summary: GH-${{ github.event.issue.number }}. ${{ github.event.issue.title }}
        description: |
          ${{ github.event.issue.html_url }}
          ${{ github.event.issue.body }}
          

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"