name: Bump version on Merge

on:
  push:
    branches:
      - csl-action-pump-ver # TODO: reverse

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Calculate next version
        run: |
            # Get the current version from the subdirectory's package.json
            current_version=$(jq -r '.version' package.json)

            # Calculate and append the next version directly into GITHUB_ENV in one line
            echo "NEXT_VERSION=$(echo "$current_version" | awk -F'[-.]' '{print $1"."$2"."$3"-minswap."$5+1}')" >> "$GITHUB_ENV"

      - name: Install dependencies
        run: |
          npm install --ignore-scripts
          npm install -g wasm-pack
          
      - name: Bump version and publish
        run: |
          ./scripts/pump-version.sh ${{ env.NEXT_VERSION }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
